In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# 학습 데이터 셋 : 예측을 위해 사용하는 데이터 셋
x_train = torch.FloatTensor([[1], [2], [3], [4]])
y_train = torch.FloatTensor([[50], [70], [90], [85]]) 

In [2]:
# y = W(Weight)x + b(bias)
# 비용함수(cost function), 손실함수(loss function), 오차함수(error function)
'''
y = 20x + 15

시간    1   2   3   4
실제값  50  70  90  85
예측값  35  55  75  95
-----------------------
오차    15  15  15  -10
'''
# 오차 값을 찾아주는 것이 오차함수
# 오차를 모두 더하면 덧셈 과정에서 오차 값에 +, -가 있어 오차의 크기를 측정할 수 없음
# 오차들을 제곱해줌
# 평균 제곱 오차 mse(Mean Squared Error) : 오차를 제곱하고 평균을 내는 것

'\ny = 20x + 15\n\n시간    1   2   3   4\n실제값  50  70  90  85\n예측값  35  55  75  95\n-----------------------\n오차    15  15  15  -10\n'

In [3]:
# 옵티마이저(optimizer)
# 비용함수의 값을 최소로 하는 W(기울기)와 b(절편)을 찾는 방법(알고리즘)

# 학습(training)
# 옵티마이저를 통해 적절한 W와 b를 찾아내는 과정

# 경사하강법(Gradient Descent)
# 가장 기본적인 옵티마이저 알고리즘
# 비용 - 기울기. 그래프를 그려보면 U자 모양
# cost가 최소화 되는 지점은 접선의 기울기가 0이 되는 지점이며, 미분값이 0이 되는 지점
# 경사 하강법은 비용 함수를 미분하여 현재 W에서의 접선의 기울기를 구하고, 접선의 기울기가 낮은 방향으로 W의 값을 업데이트 하는 작업을 반복

# 학습률(learning rate)
# 기울기의 값을 변경할 때 얼마나 크게 변경할지를 결정

In [4]:
# 코드를 재실행해도 같은 랜덤 결과가 나옴
torch.manual_seed(10)

In [5]:
# x_train 값과 x_train의 shape를 출력
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.],
        [4.]])
torch.Size([4, 1])


In [6]:
# y_train 값과 y_train의 shape를 출력
print(y_train)
print(y_train.shape)

tensor([[50.],
        [70.],
        [90.],
        [85.]])
torch.Size([4, 1])


In [7]:
# 선형 회귀의 핵심은 학습데이터와 가장 가장 잘 맞는 직선을 찾는 작업
# requires_grad=True : 학습을 통해 계속 값이 변경되는 변수
W = torch.zeros(1, requires_grad=True)  # 1 : 데이터 하나
print(W)

b = torch.zeros(1, requires_grad=True)
print(b)

# y = 0*x + 0
H = x_train * W + b # 가설

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [8]:
# 비용 함수 선언
cost = torch.mean((H - y_train) ** 2)
print(cost)

tensor(5681.2500, grad_fn=<MeanBackward0>)


In [9]:
optimizer = optim.SGD([W, b], lr=0.01)  # lr : 학습률

In [10]:
# gradient를 0으로 초기화
optimizer.zero_grad()

#비용함수를 미분하여 gradient 계산. 역전파
cost.backward()

# W와 b를 업데이트
optimizer.step()

In [11]:
# 총 에폭은 2000번, 100번마다 로그 출력
# epoch : 전체 훈련 데이터가 학습에 한 번 사용된 주기

x_train = torch.FloatTensor([[1], [2], [3], [4]])
y_train = torch.FloatTensor([[50], [70], [90], [85]])

W = torch.zeros(1, requires_grad=True)  # 1 : 데이터 하나
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=0.01)  # lr : 학습률

for epoch in range(2000):
  H = x_train * W + b 
  cost = torch.mean((H - y_train) ** 2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} W : {:.3f}, b : {:.3f} Cost : {:.6f}'.format(epoch, 2000, W.item(), b.item(), cost.item()))


Epoch    0/2000 W : 4.000, b : 1.475 Cost : 5681.250000
Epoch  100/2000 W : 21.114, b : 17.175 Cost : 154.635162
Epoch  200/2000 W : 18.882, b : 23.736 Cost : 106.034019
Epoch  300/2000 W : 17.229, b : 28.597 Cost : 79.352539
Epoch  400/2000 W : 16.004, b : 32.199 Cost : 64.704773
Epoch  500/2000 W : 15.096, b : 34.867 Cost : 56.663338
Epoch  600/2000 W : 14.424, b : 36.845 Cost : 52.248714
Epoch  700/2000 W : 13.925, b : 38.310 Cost : 49.825111
Epoch  800/2000 W : 13.556, b : 39.395 Cost : 48.494576
Epoch  900/2000 W : 13.282, b : 40.200 Cost : 47.764103
Epoch 1000/2000 W : 13.080, b : 40.796 Cost : 47.363113
Epoch 1100/2000 W : 12.930, b : 41.237 Cost : 47.142975
Epoch 1200/2000 W : 12.818, b : 41.564 Cost : 47.022110
Epoch 1300/2000 W : 12.736, b : 41.807 Cost : 46.955765
Epoch 1400/2000 W : 12.675, b : 41.986 Cost : 46.919334
Epoch 1500/2000 W : 12.629, b : 42.119 Cost : 46.899345
Epoch 1600/2000 W : 12.596, b : 42.218 Cost : 46.888405
Epoch 1700/2000 W : 12.571, b : 42.291 Cost : 

In [12]:
model = nn.Linear(1, 1)

In [13]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1, 1)

  def forward(self, x):
    return self.linear(x)

In [15]:
x_train = torch.FloatTensor([[1], [2], [3], [4]])
y_train = torch.FloatTensor([[50], [70], [90], [85]]) 

In [16]:
model = LinearRegressionModel()

In [17]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [18]:
for epoch in range(1, 2001):
  H = model(x_train)
  #cost = torch.mean((H - y_train) ** 2)
  cost = F.mse_loss(H, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} W : {:.3f}, b : {:.3f} Cost : {:.6f}'.format(epoch, 2000, W.item(), b.item(), cost.item()))

Epoch  100/2000 W : 12.529, b : 42.415 Cost : 153.265686
Epoch  200/2000 W : 12.529, b : 42.415 Cost : 105.282211
Epoch  300/2000 W : 12.529, b : 42.415 Cost : 78.939957
Epoch  400/2000 W : 12.529, b : 42.415 Cost : 64.478210
Epoch  500/2000 W : 12.529, b : 42.415 Cost : 56.538986
Epoch  600/2000 W : 12.529, b : 42.415 Cost : 52.180420
Epoch  700/2000 W : 12.529, b : 42.415 Cost : 49.787621
Epoch  800/2000 W : 12.529, b : 42.415 Cost : 48.473969
Epoch  900/2000 W : 12.529, b : 42.415 Cost : 47.752815
Epoch 1000/2000 W : 12.529, b : 42.415 Cost : 47.356934
Epoch 1100/2000 W : 12.529, b : 42.415 Cost : 47.139538
Epoch 1200/2000 W : 12.529, b : 42.415 Cost : 47.020203
Epoch 1300/2000 W : 12.529, b : 42.415 Cost : 46.954765
Epoch 1400/2000 W : 12.529, b : 42.415 Cost : 46.918800
Epoch 1500/2000 W : 12.529, b : 42.415 Cost : 46.899036
Epoch 1600/2000 W : 12.529, b : 42.415 Cost : 46.888199
Epoch 1700/2000 W : 12.529, b : 42.415 Cost : 46.882233
Epoch 1800/2000 W : 12.529, b : 42.415 Cost : 