In [1]:
# 공부한 시간, 학원에서 공부한 시간, 과외 시간, 점수
'''
공부한시간        2   2   2   3   4   4
학원 공부한 시간  0   1   2   1   1   2
과외 시간         0   0   1   1   2   2
실제 값           50  60  65  70  75  85
'''
# 일반 선형 회귀 : H = wx + b
# 다중 선형 회귀 : H = w1x1 + w2x2 + w3x3 + b

'\n공부한시간        2   2   2   3   4   4\n학원 공부한 시간  0   1   2   1   1   2\n과외 시간         0   0   1   1   2   2\n실제 값           50  60  65  70  75  85\n'

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
torch.manual_seed(10)

In [4]:
# 시드 예

torch.manual_seed(7)
print('랜덤 시드 : 7')
for i in  range(1,3):
  print(torch.rand(1))

랜덤 시드 : 7
tensor([0.5349])
tensor([0.1988])


In [5]:
torch.manual_seed(9)
print('랜덤 시드 : 9')
for i in  range(1,3):
  print(torch.rand(1))

랜덤 시드 : 9
tensor([0.6558])
tensor([0.3020])


In [6]:
torch.manual_seed(7)
print('랜덤 시드 : 7')
for i in  range(1,3):
  print(torch.rand(1))

  # 같은 시드끼리 랜덤 값 고정

랜덤 시드 : 7
tensor([0.5349])
tensor([0.1988])


In [7]:
x1_train = torch.FloatTensor([[2], [2], [2], [3], [4], [4]])
x2_train = torch.FloatTensor([[0], [1], [2], [1], [1], [2]])
x3_train = torch.FloatTensor([[0], [0], [1], [1], [2], [2]])
y_train = torch.FloatTensor([[50], [60], [65], [70], [75], [85]])

In [8]:
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [9]:
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)
tot_epochs = 1000

for epoch in range(1, tot_epochs+1):
  H = x1_train * w1 + x2_train * w2 + x3_train * w3 + b
  cost = torch.mean((H-y_train) ** 2)
  
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} w1 : {:.3f}, w2 : {:.3f}, w3 : {:.3f}, b : {:.3f} Cost : {:.6f}'.format(epoch, 2000, w1.item(), w2.item(), w3.item(), b.item(), cost.item()))


Epoch  100/2000 w1 : 0.395, w2 : 0.166, w3 : 0.150, b : 0.133 Cost : 4457.451660
Epoch  200/2000 w1 : 0.780, w2 : 0.328, w3 : 0.295, b : 0.264 Cost : 4244.458496
Epoch  300/2000 w1 : 1.156, w2 : 0.487, w3 : 0.437, b : 0.391 Cost : 4041.941406
Epoch  400/2000 w1 : 1.522, w2 : 0.641, w3 : 0.575, b : 0.515 Cost : 3849.384766
Epoch  500/2000 w1 : 1.879, w2 : 0.792, w3 : 0.709, b : 0.636 Cost : 3666.297852
Epoch  600/2000 w1 : 2.228, w2 : 0.938, w3 : 0.840, b : 0.755 Cost : 3492.215576
Epoch  700/2000 w1 : 2.567, w2 : 1.082, w3 : 0.967, b : 0.870 Cost : 3326.694092
Epoch  800/2000 w1 : 2.899, w2 : 1.221, w3 : 1.091, b : 0.983 Cost : 3169.312500
Epoch  900/2000 w1 : 3.222, w2 : 1.358, w3 : 1.212, b : 1.094 Cost : 3019.669189
Epoch 1000/2000 w1 : 3.537, w2 : 1.491, w3 : 1.329, b : 1.201 Cost : 2877.384521


In [10]:
# 변수가 많으면 가설식(H)이 복잡해짐 => dot product 함수 사용

In [11]:
# 벡터의 내적(Dot Product)를 사용하여 학습
x_train = torch.FloatTensor([[2, 0, 0],
                             [2, 1, 0],
                             [2, 2, 1],
                             [3, 1, 1],
                             [4, 1, 2],
                             [4, 2, 2]])
y_train = torch.FloatTensor([[50], [60], [65], [70], [75], [85]])

In [12]:
print(x_train.shape)
print(y_train.shape)

torch.Size([6, 3])
torch.Size([6, 1])


In [13]:
W = torch.zeros((3,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=1e-5)

epoch_count = 300
for epoch in range(epoch_count+1):
  H = x_train.matmul(W) + b # matmul : 파이썬 내장함수

  cost = torch.mean((H - y_train) ** 2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  print('Epoch {:4d}/{} H:{} cost: {:.6f}'.format(
      epoch, epoch_count, H.squeeze().detach(), cost.item() #squeeze : 차원 축소, detach : remove와 비슷 하지만 삭제된 것 저장됌
  ))

Epoch    0/300 H:tensor([0., 0., 0., 0., 0., 0.]) cost: 4679.166504
Epoch    1/300 H:tensor([0.0093, 0.0110, 0.0142, 0.0166, 0.0221, 0.0237]) cost: 4676.871094
Epoch    2/300 H:tensor([0.0187, 0.0221, 0.0285, 0.0331, 0.0441, 0.0475]) cost: 4674.577148
Epoch    3/300 H:tensor([0.0280, 0.0331, 0.0427, 0.0496, 0.0662, 0.0712]) cost: 4672.283691
Epoch    4/300 H:tensor([0.0374, 0.0441, 0.0569, 0.0662, 0.0882, 0.0950]) cost: 4669.992676
Epoch    5/300 H:tensor([0.0467, 0.0551, 0.0711, 0.0827, 0.1103, 0.1187]) cost: 4667.701660
Epoch    6/300 H:tensor([0.0561, 0.0662, 0.0853, 0.0992, 0.1323, 0.1424]) cost: 4665.411621
Epoch    7/300 H:tensor([0.0654, 0.0772, 0.0996, 0.1158, 0.1543, 0.1661]) cost: 4663.123535
Epoch    8/300 H:tensor([0.0747, 0.0882, 0.1138, 0.1323, 0.1764, 0.1898]) cost: 4660.836426
Epoch    9/300 H:tensor([0.0841, 0.0992, 0.1280, 0.1488, 0.1984, 0.2135]) cost: 4658.550293
Epoch   10/300 H:tensor([0.0934, 0.1102, 0.1422, 0.1653, 0.2204, 0.2372]) cost: 4656.265137
Epoch   11/3