In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
x_train = torch.FloatTensor([[1], [2], [3], [4]])
y_train = torch.FloatTensor([[50], [70], [90], [85]]) 

In [3]:
# 단순 선형 회귀는 input=1, output=1
model =  nn.Linear(1, 1)  # weight, bias 모두 Linear에 들어있음

In [4]:
print(list(model.parameters())) # w, b 임의의 값 출력

[Parameter containing:
tensor([[0.7791]], requires_grad=True), Parameter containing:
tensor([0.4348], requires_grad=True)]


In [6]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [9]:
epoch_count = 3000

for epoch in range(epoch_count+1):
  H = model(x_train)

  cost = F.mse_loss(H, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, epoch_count, cost.item()))

Epoch    0/3000 Cost: 46.875000
Epoch  100/3000 Cost: 46.875000
Epoch  200/3000 Cost: 46.875000
Epoch  300/3000 Cost: 46.875000
Epoch  400/3000 Cost: 46.875000
Epoch  500/3000 Cost: 46.875000
Epoch  600/3000 Cost: 46.875000
Epoch  700/3000 Cost: 46.875000
Epoch  800/3000 Cost: 46.875000
Epoch  900/3000 Cost: 46.875000
Epoch 1000/3000 Cost: 46.875000
Epoch 1100/3000 Cost: 46.875000
Epoch 1200/3000 Cost: 46.875000
Epoch 1300/3000 Cost: 46.875000
Epoch 1400/3000 Cost: 46.875000
Epoch 1500/3000 Cost: 46.875000
Epoch 1600/3000 Cost: 46.875000
Epoch 1700/3000 Cost: 46.875000
Epoch 1800/3000 Cost: 46.875000
Epoch 1900/3000 Cost: 46.875000
Epoch 2000/3000 Cost: 46.875000
Epoch 2100/3000 Cost: 46.875000
Epoch 2200/3000 Cost: 46.875000
Epoch 2300/3000 Cost: 46.875000
Epoch 2400/3000 Cost: 46.875000
Epoch 2500/3000 Cost: 46.875000
Epoch 2600/3000 Cost: 46.875000
Epoch 2700/3000 Cost: 46.875000
Epoch 2800/3000 Cost: 46.875000
Epoch 2900/3000 Cost: 46.875000
Epoch 3000/3000 Cost: 46.875000


In [10]:
var = torch.FloatTensor([[5.0]])
pred = model(var)
print('학습 후 입력이 5일 때 예측 값 :', pred)

학습 후 입력이 5일 때 예측 값 : tensor([[105.0004]], grad_fn=<AddmmBackward0>)


In [12]:
print(list(model.parameters()))

[Parameter containing:
tensor([[12.5002]], requires_grad=True), Parameter containing:
tensor([42.4994], requires_grad=True)]


In [ ]:
# 다중 선형 회귀

In [13]:
x_train = torch.FloatTensor([[2, 0, 0],
                             [2, 1, 0],
                             [2, 2, 1],
                             [3, 1, 1],
                             [4, 1, 2],
                             [4, 2, 2]])
y_train = torch.FloatTensor([[50], [60], [65], [70], [75], [85]])

In [23]:
model =  nn.Linear(3, 1)  # 3 : w, 1 : b

In [24]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.2110, -0.5766, -0.5694]], requires_grad=True), Parameter containing:
tensor([-0.0705], requires_grad=True)]


In [25]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)  

In [28]:
epoch_count = 100000

for epoch in range(epoch_count+1):
  H = model(x_train)

  cost = F.mse_loss(H, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, epoch_count, cost.item()))

Epoch    0/100000 Cost: 1187.578491
Epoch  100/100000 Cost: 1135.146118
Epoch  200/100000 Cost: 1085.287476
Epoch  300/100000 Cost: 1037.875122
Epoch  400/100000 Cost: 992.789307
Epoch  500/100000 Cost: 949.915100
Epoch  600/100000 Cost: 909.144287
Epoch  700/100000 Cost: 870.372986
Epoch  800/100000 Cost: 833.503113
Epoch  900/100000 Cost: 798.440857
Epoch 1000/100000 Cost: 765.097656
Epoch 1100/100000 Cost: 733.387878
Epoch 1200/100000 Cost: 703.231934
Epoch 1300/100000 Cost: 674.553101
Epoch 1400/100000 Cost: 647.278687
Epoch 1500/100000 Cost: 621.339539
Epoch 1600/100000 Cost: 596.670044
Epoch 1700/100000 Cost: 573.207703
Epoch 1800/100000 Cost: 550.893311
Epoch 1900/100000 Cost: 529.669861
Epoch 2000/100000 Cost: 509.484009
Epoch 2100/100000 Cost: 490.284668
Epoch 2200/100000 Cost: 472.022980
Epoch 2300/100000 Cost: 454.653442
Epoch 2400/100000 Cost: 438.131622
Epoch 2500/100000 Cost: 422.415924
Epoch 2600/100000 Cost: 407.466919
Epoch 2700/100000 Cost: 393.246582
Epoch 2800/10000

In [29]:
var = torch.FloatTensor([[5, 2, 3]])
pred = model(var)
print('학습 후 입력이 5, 2, 3 일 때 :',pred)  # 에폭 : 3000 => 59.4 / 에폭 : 100000 => 105.4

학습 후 입력이 5, 2, 3 일 때 : tensor([[105.3917]], grad_fn=<AddmmBackward0>)


In [30]:
print(list(model.parameters()))

[Parameter containing:
tensor([[16.5129,  8.5105, -1.5541]], requires_grad=True), Parameter containing:
tensor([10.4683], requires_grad=True)]
