##1. 텐서플로우(TensorFlow)와 케라스(Keras)
- 텐서플로우와 케라스는 ML모델을 개발하고 학습시키는데 도움이 되는 핵심 오픈소스 라이브러리
- 케라스는 사용자가 텐서플로우를 좀 더 쉽고 편하게 사용할 수 있게 해주는 high level API를 제공
- 텐서플로우 2.x에서는 케라스를 딥러닝의 공식 API로 채택하였고, 텐서플로우 내의 하나의 프레임워크로 개발되고 있음

In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
print(tf.__version__)
print(keras.__version__)

2.8.0
2.8.0


###1-1. Tensor
- Tensor는 multi-dimensional array를 나타내는 말
- Tensorflow의 기본 data type

In [4]:
hellotf = tf.constant([3, 3], dtype=tf.float32)
print(hellotf)

hellotf = tf.constant('Hello Tensor!!')
print(hellotf)  # b'' => b : bite

tf.Tensor([3. 3.], shape=(2,), dtype=float32)
tf.Tensor(b'Hello Tensor!!', shape=(), dtype=string)


In [5]:
x = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])
print(x)
print(type(x))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [6]:
import numpy as np

In [8]:
x_np = np.array([[1.0, 2.0],
                 [3.0, 4.0]])
x_list = [[1.0, 2.0],
          [3.0, 4.0]]

print(type(x_np))
print(type(x_list))

<class 'numpy.ndarray'>
<class 'list'>


In [10]:
x_np = tf.convert_to_tensor(x_np)
x_list = tf.convert_to_tensor(x_list)

print(type(x_np))
print(type(x_list))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [11]:
# tensor를 numpy ndarray로 바꿈
x.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [12]:
print(type(x.numpy()))

<class 'numpy.ndarray'>


###1-2. 텐서플로우 함수

In [15]:
a = tf.ones((2,3))
print(a)

b = tf.zeros((2,3))
print(b)

c = tf.fill((2,3), 2)
print(c)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2 2 2]
 [2 2 2]], shape=(2, 3), dtype=int32)


In [17]:
# shape, dtype 복사
d = tf.zeros_like(c)  
print(d)

e = tf.ones_like(c)
print(e)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [18]:
g = tf.range(10)
print(g)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [21]:
h = tf.random.uniform((2, 2)) # 0~1 사이의 양수 값
print(h)

i = tf.random.normal((2, 2))  # -2~2 사이의 음, 양수 값
print(i)

tf.Tensor(
[[0.68501675 0.57241654]
 [0.09543204 0.9218948 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.7555621  -0.23687793]
 [-1.6673242   1.6946446 ]], shape=(2, 2), dtype=float32)


###1-3. Tensor의 속성

In [22]:
tensor = tf.random.normal((3,4))
print(f'shape : {tensor.shape}')
print(f'DataType : {tensor.dtype}')

shape : (3, 4)
DataType : <dtype: 'float32'>


In [23]:
tensor = tf.reshape(tensor, (4,3))
tensor = tf.cast(tensor, tf.int32)
print(f'shape : {tensor.shape}')
print(f'DataType : {tensor.dtype}')

shape : (4, 3)
DataType : <dtype: 'int32'>


###1-4. Variable
- Variable은 변할 수 있는 상태를 저장하는데 사용되는 특별한 텐서
- 딥러닝에서는 학습해야 하는 가중치(weight, bias)들을 variable로 생성
- weight : 기울기
- bias : 절편

In [24]:
tensor = tf.ones((3,4))
print(tensor)

tensor[0,0] = 2 # tensor변수 안에 저장된 데이터값은 상수 개념이라서 값을 바꿀수 없음

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


TypeError: ignored

In [26]:
variable = tf.Variable(tensor)  # tensor변수 안에 데이터값을 변수로 바꿈
print(variable)

variable[0,0].assign(2) # tensor변수 안에 [0,0] 위치에 있는 데이터 값을 2로 바꿈
print(variable)

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[2., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>


In [28]:
initial_value = tf.random.normal(shape=(2,2))
weight = tf.Variable(initial_value)
print(weight)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.28821933,  0.6715007 ],
       [ 1.9560354 ,  0.5377496 ]], dtype=float32)>


In [32]:
# assign(value) : 값 설정
# assign_add(increment) : 더하기
# assign_sub(decrement) : 빼기
new_value = tf.random.normal(shape=(2,2))
print(new_value)
weight.assign(new_value)
print(weight)

ones_value = tf.ones(shape=(2, 2))
weight.assign_sub(ones_value)
print(weight)

tf.Tensor(
[[-1.8156737  0.7462533]
 [-0.5135712  1.4202594]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-1.8156737,  0.7462533],
       [-0.5135712,  1.4202594]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.8156738 , -0.2537467 ],
       [-1.5135713 ,  0.42025936]], dtype=float32)>


###1-5. Indexing과 Slicing

In [31]:
a = tf.range(1, 13)
print(a)

a = tf.reshape(a, (3, 4))
print(a)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)


In [33]:
# indexing : 인덱싱을 하게 되면 차원이 감소하게 됨
print(a[1])
print(a[0,-1])

tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [35]:
# slicing : 슬라이싱은 차원이 유지됨
print(a[1:-1])
print(a[:2, 2:])

tf.Tensor([[5 6 7 8]], shape=(1, 4), dtype=int32)
tf.Tensor(
[[3 4]
 [7 8]], shape=(2, 2), dtype=int32)


###1-6. Transpose(차원 바꾸기)

In [36]:
a = tf.range(16)
print(a)
a = tf.reshape(a, (2, 2, -1)) # (면, 행, 열): -1은 자동으로 만들라는 뜻
print(a)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15], shape=(16,), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]], shape=(2, 2, 4), dtype=int32)


In [37]:
print(a)
# transpose(전치할 행렬, 차원의 순서, [오퍼레이션 명칭])
# a.shape의 리스트의 인덱스값으로 transpose.shape 설정
# shape=(2,2,4) (transpose)=> (a[2],a[0],a[1])
# a.shape=(2,2,4) => transpose.shape=(4,2,2)
b = tf.transpose(a, (2, 0,1)) 
print(b)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]], shape=(2, 2, 4), dtype=int32)
tf.Tensor(
[[[ 0  4]
  [ 8 12]]

 [[ 1  5]
  [ 9 13]]

 [[ 2  6]
  [10 14]]

 [[ 3  7]
  [11 15]]], shape=(4, 2, 2), dtype=int32)


###1-7. Tensor 연산

In [40]:
x = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
y = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)
print(x)
print(y)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)


In [41]:
print(tf.add(x,y))
print(tf.subtract(x,y))
print(tf.multiply(x,y))
print(tf.divide(x,y))
print(tf.matmul(x,y))
print('*'*50)
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x@y)

tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
**************************************************
tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [42]:
z= tf.range(1, 11)
print(z)
z = tf.reshape(z, (2, 5))
print(z)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(2, 5), dtype=int32)


In [43]:
print(tf.reduce_sum(z)) # 요소의 합계

tf.Tensor(55, shape=(), dtype=int32)


In [46]:
sum1 = tf.reduce_sum(z, axis=0) # 행으로 합계
print(sum1)
sum2 = tf.reduce_sum(z, axis=1) # 열끼리 합
print(sum2)
sum3 = tf.reduce_sum(z, axis=-1)  #열끼리 합
print(sum3)

tf.Tensor([ 7  9 11 13 15], shape=(5,), dtype=int32)
tf.Tensor([15 40], shape=(2,), dtype=int32)
tf.Tensor([15 40], shape=(2,), dtype=int32)


In [49]:
concat1 = tf.concat([z, z], axis=0)  # 행방향으로 합치기
print(concat1)
concat2 = tf.concat([z, z], axis=1) # 열방향으로 합치기
print(concat2)
concat3 = tf.concat([z, z], axis=-1)  # axis: 2차(행, 열) / 3차(행, 열, 면) => 2차이기 때문에 마지막 인덱스인 열방향으로 합치기
print(concat3)

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(4, 5), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]], shape=(2, 10), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]], shape=(2, 10), dtype=int32)
