##1. 파이토치(Pytorch)
- Pytorch는 tensorflow와 함께 딥러닝에서 가장 널리 사용되는 framework
- 초기에는 Torch라는 이름으로 Lua언어 기반으로 만들어졌으나, 이후 Python 기반으로 변경한 것이 Pytorch
- NewYork 대학교와 FaceBook이 공동으로 개발하였고, 가장 대중적이면서 널리 사용되는 framework

In [1]:
import torch
print(torch.__version__)

1.11.0+cu113


###1-1. Tensor
- 텐서(tensor)는 배열(array)이나 행렬(matrix)과 매우 유사한 특수 자료구조
- Pytorch에서는 텐서를 사용하여 모델의 입력(input)과 출력(output) 그리고 모델의 매개변수들을 부호화(encode)함

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [3]:
import numpy as np

In [4]:
np_array = np.array(data)
x_np_1 = torch.tensor(np_array) # 카피를 만듬(새로운 텐서, 메모리낭비)
print(x_np_1)

tensor([[1, 2],
        [3, 4]])


In [5]:
x_np_1[0, 0] = 10
print(x_np_1)
print(np_array) # 데이터값 안바뀜

tensor([[10,  2],
        [ 3,  4]])
[[1 2]
 [3 4]]


In [6]:
x_np_2 = torch.as_tensor(np_array)  # 뷰를 만듬. 형식이 리스트여도 상관없음
print(x_np_2)

tensor([[1, 2],
        [3, 4]])


In [7]:
x_np_2[0, 0] = 10
print(x_np_2)
print(np_array)

tensor([[10,  2],
        [ 3,  4]])
[[10  2]
 [ 3  4]]


In [8]:
x_np_3 = torch.from_numpy(np_array) # 뷰를 만듬. 무조건 numpy 형식이여야함
print(x_np_3)

tensor([[10,  2],
        [ 3,  4]])


In [9]:
x_np_3[0, 0] = 20
print(x_np_3)
print(np_array)

tensor([[20,  2],
        [ 3,  4]])
[[20  2]
 [ 3  4]]


In [10]:
# 텐서 -> ndArray
np_again = x_np_1.numpy()
print(np_again, type(np_again))

[[10  2]
 [ 3  4]] <class 'numpy.ndarray'>


In [11]:
a = torch.ones(2, 3)
print(a)

b = torch.zeros(2, 3)
print(b)

c = torch.full((2, 3), 2)
print(c)

d = torch.empty(2, 3) # 음, 양 모든 수 랜덤
print(d)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[2, 2, 2],
        [2, 2, 2]])
tensor([[2.9838e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 1.0000e+00]])


In [12]:
i = torch.eye(3)  # 단위행렬(크기)
print(i)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [13]:
j = torch.arange(10)
print(j)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [14]:
k = torch.rand(2, 2)
l = torch.randn(2, 2) # -2 ~ 2 랜덤
print(k)
print(l)

tensor([[0.4530, 0.4955],
        [0.0108, 0.5136]])
tensor([[-1.8594, -0.5067],
        [-1.3685, -0.2423]])


###1-2. Tensor 속성

In [15]:
tensor = torch.rand(3, 4)

print(f'Shape of tensor : {tensor.shape}')
print(f'DataType of tensor : {tensor.dtype}')
print(f'Device of tensor : {tensor.device}')

Shape of tensor : torch.Size([3, 4])
DataType of tensor : torch.float32
Device of tensor : cpu


In [17]:
# 속성 변경
tensor = tensor.reshape(4, 3)
tensor = tensor.int()
if torch.cuda.is_available(): # gpu 사용가능 여부
  tensor = tensor.to('cuda')  # cpu에 있는 변수를 gpu로 넘김. 런타임 유형변경에서 하드웨어 가속기 gpu로 설정 -> 런타임 다시 시작

print(f'Shape of tensor : {tensor.shape}')
print(f'DataType of tensor : {tensor.dtype}')
print(f'Device of tensor : {tensor.device}')

Shape of tensor : torch.Size([4, 3])
DataType of tensor : torch.int32
Device of tensor : cuda:0


###1-3. Indexing과 Slicing

In [18]:
a = torch.arange(1, 13).reshape(3, 4)
print(a)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [19]:
print(a[1])
print(a[0, -1])

tensor([5, 6, 7, 8])
tensor(4)


In [20]:
print(a[1:-1])

tensor([[5, 6, 7, 8]])


In [21]:
print(a[:2, 2:])

tensor([[3, 4],
        [7, 8]])


###1-4. Transpose

In [22]:
a = torch.arange(16).reshape(2, 2, 4)
print(a, a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]]) torch.Size([2, 2, 4])


In [23]:
b = a.transpose(1, 2) # a.shape=(2,2,4)의 인덱스로 크기 설정 => (a[1], a[2])=(2,4). a[0]은 생략 => 자동 설정
print(b, b.shape)

tensor([[[ 0,  4],
         [ 1,  5],
         [ 2,  6],
         [ 3,  7]],

        [[ 8, 12],
         [ 9, 13],
         [10, 14],
         [11, 15]]]) torch.Size([2, 4, 2])


In [24]:
c = a.permute((2, 0, 1))  # permute(a[2], a[0], a[1]) => shape=(4,2,2)
print(c, c.shape)

tensor([[[ 0,  4],
         [ 8, 12]],

        [[ 1,  5],
         [ 9, 13]],

        [[ 2,  6],
         [10, 14]],

        [[ 3,  7],
         [11, 15]]]) torch.Size([4, 2, 2])


###1-5. Tensor 연산

In [25]:
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
y = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)
print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [27]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x @ y)
print('*'*30)
print(torch.add(x,y))
print(torch.subtract(x, y))
print(torch.multiply(x, y))
print(torch.divide(x, y))
print(torch.matmul(x, y))

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])
******************************
tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])


In [28]:
# in-place 연산
print(x.add(y))
print(x)

print(x.add_(y))  # x에 결과를 다시 저장 (x += 10) => x와 x+y 결과값이 나옴

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 6.,  8.],
        [10., 12.]])


In [30]:
z = torch.arange(1, 11).reshape(2, 5)
print(z)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


In [31]:
sum1 = torch.sum(z, axis=0)
sum2 = torch.sum(z, axis=1)
sum3 = torch.sum(z, axis=-1)
print(sum1, sum1.shape)
print(sum2, sum2.shape)
print(sum3, sum3.shape)

tensor([ 7,  9, 11, 13, 15]) torch.Size([5])
tensor([15, 40]) torch.Size([2])
tensor([15, 40]) torch.Size([2])


In [32]:
a = torch.arange(24).reshape(4,6)
b = a.clone().detach()  # clone : 복사 / detach : 붙여넣기(변수에 넣어줌)
print(a, a.shape)
print(b, b.shape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([4, 6])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([4, 6])
